### ISSUE TITLE
False positive: TLD of cosmetic rules considered as dead domain

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DeadDomainsLinter#10]
![image](https://github.com/AdguardTeam/DeadDomainsLinter/assets/8361299/58526153-e376-430a-b428-7dc91dea7a93)

`tld##example.com` is a valid rule

**Comment by scripthunter7** [comment]
Andrey already fixed this, just the PR does not merged yet
See https://github.com/AdguardTeam/DeadDomainsLinter/commit/036ff59895fdf4416fb6537b7165c5ef1fc8594e
