### ISSUE TITLE
Ctrl-C does not abort the script

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DeadDomainsLinter#15]
Windows 10 x64, default `cmd.exe`

It seems `Ctrl-C` works like Enter

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/DeadDomainsLinter/assets/8361299/8b18b2dc-239a-4da0-85a8-a54df4bd35e7)

</details>

**Comment by ameshkov** [comment]
You need to use Ctrl+D :)

**Comment by Alex-302** [comment]
Old good `Ctrl-Break` also works)
