### ISSUE TITLE
Add an option to supply the dead domains list as an argument

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DeadDomainsLinter#20]
In order to make the run more reliable, we could use the following approach:

1. First run: export the list of dead domains (will need #8 for that).
2. Second run after several months: again export the list of dead domains.
3. Compare them and compile a list of domains that are in both the old and the new list.
4. Final run: supply the list of dead domains and remove only them.

**Comment by abidjauhar17** [comment]
@ameshkov Is this tool for finding dead domains no longer being developed? this tool is very useful
