### ISSUE TITLE
Import domains list does not work.

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DeadDomainsLinter#23]
Export to `D:\domains.txt` works. But when I tying to import, domains from the list no removed from filters.

Tried
`dead-domains-linter --import=D:\domains.txt --auto`
`dead-domains-linter --import=domains.txt --auto` - `domains.txt` in the current dir.

**Comment by ameshkov** [comment]
Do you see any error in the output?

**Comment by Alex-302** [comment]
No, just `Analyzed *** rules, found 0 issues`

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/DeadDomainsLinter/assets/8361299/2b032b29-676d-4b0e-b97b-676b55f9e84e)

</details>

Non-existing file check works

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/DeadDomainsLinter/assets/8361299/22ede9d7-973c-406d-8f12-5ebd31157a4d)

</details>

**Comment by ameshkov** [comment]
So the first command worked and there's one domain in the file. What domain are you trying to remove and which rules aren't removed?

**Comment by Alex-302** [comment]
I collected domains from all our filters to test export/import feature.

More than 3k rules in the file
[domains.txt](https://github.com/AdguardTeam/DeadDomainsLinter/files/14125939/domains.txt)

**Comment by ameshkov** [comment]
Hm, according to the log it found 1 domain there:)

**Comment by ameshkov** [comment]
Argh, that was a stupid bug

**Comment by Alex-302** [comment]
Random domains from the list, which are in my list
10co.biz
1tamilblasters.lat
