### ISSUE TITLE
 Failed to process specific.txt due to SystemError

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/DeadDomainsLinter#26]
DDL always stops when processing specifix.txt in Base filter with this error:
> ERROR  Failed to process specific.txt due to SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)

Not sure if is relevant but PyFunceble (or generally Python) had a similar problem caused by cp932 encoding which Windows uses on Japanese installaion https://github.com/funilrys/PyFunceble/issues/155#issuecomment-751268123
 
<details>
<summary>Screenshot</summary>

![err](https://github.com/AdguardTeam/DeadDomainsLinter/assets/58900598/03058be0-961f-477f-b06b-e89b1b742e27)

</details>

**Comment by ameshkov** [comment]
MINGW console for some reason cannot work in interactive mode.

Here are the options:
1. Run DDL from PowerShell or regular cmd
2. Run DDL in "auto" mode
3. Also, maybe this solution will also work: https://github.com/docker/for-win/issues/1588#issuecomment-449421977, i.e. `alias dead-domains-linter = "winpty dead-domains-linter"`
