### ISSUE TITLE
DeadDomainLinter Labeling Entire List as Dead

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/DeadDomainsLinter#31]
I tested this by doing the following:

- Ran `hostlist-compiler -i INPUT -o OUTPUT.txt` using Pete Lowe's List as the INPUT
- OUTPUT.txt was created successfully 
- Ran `dead-domains-linter -i OUTPUT.txt --export=deadoutput.txt --dnscheck=false`
- Ran `dead-domains-linter -i OUTPUT.txt --import=deadoutput.txt --auto`
- Open OUTPUT.txt and the list is empty

Is there a site that I need to unblock? I've checked the Adguard DNS and the Adguard for Windows logs but none of them show activity of blocking anything related to DeadDomainLinter.

**Comment by ameshkov** [comment]
It relies on AdGuard DNS data which might be lagging now since we had a huge migration yesterday.

Please disregard the results until the next week.

**Comment by KnightmareVIIVIIXC** [comment]
Working again
