### ISSUE TITLE
False-positive on a rule that targets "chrome-extension://${id}"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DeadDomainsLinter#6]
`@@||evernote.com^$domain=pioclpoplcdbaefihamjohnefbikjilc`

**Comment by scripthunter7** [comment]
@ameshkov We already have a [basic domain validator in AGTree](https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/agtree/src/parser/misc/domain-list.ts)

I recommend improving this utility in the following aspects (new methods):
- validation of domains without wildcards, like wildcard TLD
- add method for IPs

**Comment by scripthunter7** [comment]
@ameshkov We already have a [basic domain validator in AGTree](https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/agtree/src/parser/misc/domain-list.ts)

I recommend improving this utility in the following aspects (new methods):
- validation of domains _without_ wildcards (like wildcard TLD) and check [known TLDs](https://www.iana.org/domains/root/db)
- add method for IPs

We may can import known TLDs to a Set from [here](http://data.iana.org/TLD/tlds-alpha-by-domain.txt)

**Comment by ameshkov** [comment]
I actually specifically don't use a normal validation, it's okay to check invalid domain names too as the tool then will suggest to remove them.

We just need to exclude some things like IP addresses when it does not make sense to check them.

**Comment by Alex-302** [comment]
> IP addresses when it does not make sense to check them

at least ping check can be performed. No response = dead.
Also response can be checked response code:

`curl -I -s -X GET http://45.141.56.28/ | grep -i "HTTP/1.1 301"`
=> `HTTP/1.1 301 Moved Permanently` / `302`. But not `HTTP/1.1 403 Forbidden`.

**Comment by ameshkov** [comment]
> curl -I -s -X GET http://45.141.56.28/ | grep -i "HTTP/1.1"
> => HTTP/1.1 301 Moved Permanently / 302. But not HTTP/1.1 403 Forbidden.

There're more cases than this one.

First of all, there could be `$network` rules that can be for different ports/protocols.
Also, even when we deal with basic rules, it could be HTTPS like `https://1.1.1.1`.

> But not HTTP/1.1 403 Forbidden

This is a working IP address, what's wrong with it.
It could be answering 403 to one request and respond with 200 OK to a different one for instance.
